Bodies damping
technologists-team/hypercube pull request #39
Opened 2024-07-31 23:20 UTC by JerryImMouse

Ну, просто трение

2024-08-01 23:00 UTC, Tornado-Technology requested changes

2024-08-01 23:00 UTC, Tornado-Technology commented on Hypercube.Shared/Entities/Systems/Physics/PhysicsComponent.cs
> +    public Vector2 LinearDamping { get; set; } = new Vector2(1f, 1f);
Just use `Vector2.One`

2024-08-02 02:30 UTC, JerryImMouse commented on Hypercube.Shared/Entities/Systems/Physics/PhysicsComponent.cs
> +    public Vector2 LinearDamping { get; set; } = new Vector2(1f, 1f);
done

2024-08-02 03:44 UTC, Tornado-Technology approved these changes

2024-08-02 03:44 UTC, merged