BufferRW for networking
technologists-team/hypercube pull request #46
Opened 2024-08-10 09:21 UTC by noverd

Буффера.

2024-08-10 13:25 UTC, Tornado-Technology requested changes

2024-08-10 13:25 UTC, Tornado-Technology commented on Hypercube.Shared/Network/Buffer.cs
> +        return Data;
А в чем смысл? Передача же по ссылке

2024-08-10 13:25 UTC, Tornado-Technology commented on Hypercube.Shared/Network/WriteBuffer/WriteBuffer.Bits.cs
> +    /// <remarks>Check that there is a fixed array size. You DO NOT need to save arrays with variable length here</remarks>
Можешь сделать так?
```cs
/// <remarks>
/// Check that there is a fixed array size. You DO NOT need to save arrays with variable length here
/// </remarks>
```

2024-08-10 13:25 UTC, Tornado-Technology commented on Hypercube.Shared/Network/WriteBuffer/WriteBuffer.Numeric.cs
> +        if (bytes.Length < 12) // 96 bits is the size of BitArray
Сделаешь константу для этого?

2024-08-10 13:25 UTC, Tornado-Technology commented on Hypercube.UnitTests/Network/BufferTest.cs
> +            Assert.That(rBuf.ReadInt(), Is.EqualTo(-1984));
Ебать

2024-08-10 15:52 UTC, noverd commented on Hypercube.UnitTests/Network/BufferTest.cs
> +            Assert.That(rBuf.ReadInt(), Is.EqualTo(-1984));
Тут че не так

2024-08-10 15:53 UTC, Tornado-Technology commented on Hypercube.Shared/Network/Buffer.cs
> +        return Data;
Понял, спасибо

2024-08-11 05:19 UTC, Tornado-Technology approved these changes

2024-08-11 05:19 UTC, merged