IComparable in Vector2 and unit tests for it
technologists-team/hypercube pull request #47
Opened 2024-08-12 11:20 UTC by smellilac

Fixes #44

2024-08-12 16:03 UTC, JerryImMouse approved these changes

2024-08-13 04:11 UTC, Tornado-Technology requested changes

2024-08-13 04:11 UTC, Tornado-Technology commented on Hypercube.Math/Vectors/Vector2.cs
> +        return Length.CompareTo(other.Length);
Касаемо этого, я думал насчёт использование чистой длины, но как мне известно для большого количество итераций, взятие корня будет вызывать лаги (А мы ведь используем вектора в физике и отрисовке). Суть в том, что лучше будет  использовать ``LengthSqueared``

2024-08-13 04:11 UTC, Tornado-Technology commented on Hypercube.UnitTests/Math/CompareToTest.cs
На будущее, я пока не написал гайдлайны, если есть возможность лучше использовать `var`, вместо прямого указание типа, хоть это и не сходится с нотацией от Microsoft

2024-08-13 04:11 UTC, Tornado-Technology commented on Hypercube.UnitTests/Math/CompareToTest.cs
> +public class CompareToTest
Классы, которые мы не предполагаем, что будут наследованы (Когда либо). Мы помечаем как `sealed`

2024-08-13 04:11 UTC, Tornado-Technology commented on Hypercube.Math/Vectors/Vector2.cs
> +    public enum ComparisonType
Думаю, это может использоваться для `Vector2Int` или `Vector3` т.к. по именованию он не привязан `Vector2`, тогда нам его нужно вынести. Но данная практика мне кажется немного странной. По сколько мы и так можем легко сравнить `vector.X > a`, это не возымеет трудностей, но вот `enum` вносит непорядок в нашу реализацию, если интересно, на эту тему можно подискутировать.

2024-08-13 04:14 UTC, Tornado-Technology commented
Вообще реализация `IComparable` и переопределение операторов сравнение есть в классе `Vector2Int`, я его обновил при написании кода для ImGui, но посчитал, что будет полезным обновить и обычный `Vector2`. К сожалению сейчас не все вектора имеют общие методы. Было бы славно если бы пробелы были заполнены. Если вы хотите, я могу составить более подробное issue, если вас ещё интересует помощь.

2024-08-13 15:22 UTC, smellilac commented on Hypercube.Math/Vectors/Vector2.cs
> +        return Length.CompareTo(other.Length);
Действительно, взятие корня будет накладно по производительности. Исправлю на сравнение по квадратам площади

2024-08-13 15:35 UTC, smellilac commented on Hypercube.Math/Vectors/Vector2.cs
> +    public enum ComparisonType
Я думаю, что можно оставить этот enum в коде, но переместить его в более подходящее место.                                             


У такого подхода есть свои плюсы: 
1) Впоследствии этот enum может быть полезен и в других классах (как вы и написали в Vector2Int или Vector3 ) 
2) Реализация без этого enum выглядит достаточно топорно и не очень красиво. В данном случае можно создать отдельный метод под каждый из вариантов сравнения,
либо сделать тоже самое, но оставить CompareTo для сравнения по длине, и последний вариант - сделать нечто подобное: 
```
public int CompareTo<T>(T other, Func<Vector2, T, int> comparisonFunction)
{
    return comparisonFunction(this, other);
}
```

2024-08-13 15:37 UTC, smellilac commented
> Вообще реализация `IComparable` и переопределение операторов сравнение есть в классе `Vector2Int`, я его обновил при написании кода для ImGui, но посчитал, что будет полезным обновить и обычный `Vector2`. К сожалению сейчас не все вектора имеют общие методы. Было бы славно если бы пробелы были заполнены. Если вы хотите, я могу составить более подробное issue, если вас ещё интересует помощь.

Да, мне будет интересно помочь Вам с этой задачей

2024-08-23 05:31 UTC, Tornado-Technology commented
> > Вообще реализация `IComparable` и переопределение операторов сравнение есть в классе `Vector2Int`, я его обновил при написании кода для ImGui, но посчитал, что будет полезным обновить и обычный `Vector2`. К сожалению сейчас не все вектора имеют общие методы. Было бы славно если бы пробелы были заполнены. Если вы хотите, я могу составить более подробное issue, если вас ещё интересует помощь.
> 
> Да, мне будет интересно помочь Вам с этой задачей

Готово: #56

2024-08-25 14:53 UTC, Tornado-Technology requested changes

2024-08-25 14:53 UTC, Tornado-Technology commented on Hypercube.Math/Vectors/Vector2.cs
> +    public enum ComparisonType
Мне все же кажется что лаконичнее вызывать `vector.X.CompareTo(vlaue);` чем использовать большой енам

2024-08-26 13:09 UTC, smellilac commented on Hypercube.Math/Vectors/Vector2.cs
> +    public enum ComparisonType
> Мне все же кажется что лаконичнее вызывать `vector.X.CompareTo(vlaue);` чем использовать большой енам

Добавил реализацию, надеюсь верно Вас понял

2024-08-28 22:18 UTC, Tornado-Technology approved these changes

2024-08-28 22:18 UTC, Tornado-Technology commented
Спасибо ;3

2024-08-28 22:20 UTC, merged